apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "trivy"
  description: "trivy"
  annotations:
    github.com/project-slug: PhoenixRedflash/trivy
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/PhoenixRedflash/trivy
      title: trivy
      icon: web
spec:
  type: service
  lifecycle: experimental
  owner: "Phoenix"
